server:
  port: 7002
spring:
  application:
    name: consumer-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
      # 对应单个服务超时
      provider-server:
        connectTimeout: 1000
        readTimeout: 5000
  hystrix:
    enabled: true

management:
  server:
    port: 9999
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

