spring:
  application:
    name: eureka-client

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://u123:123456@localhost:7001/eureka/